"""empty message

Revision ID: 7e6bfa148bb9
Revises: ee9e34f49895
Create Date: 2018-12-07 18:46:47.935804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e6bfa148bb9'
down_revision = 'ee9e34f49895'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('surveys_name_key', 'surveys', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('surveys_name_key', 'surveys', ['name'])
    # ### end Alembic commands ###
