"""empty message

Revision ID: ee9e34f49895
Revises: b792bc5ecc24
Create Date: 2018-12-07 15:41:40.097147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee9e34f49895'
down_revision = 'b792bc5ecc24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=120), nullable=True))
    op.drop_constraint('users_mail_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'mail')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mail', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_mail_key', 'users', ['mail'])
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
